# Generated by Django 4.1.13 on 2024-03-25 11:32

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'auth_user',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('vehicles', 'Vehicles'), ('computers', 'Computers'), ('phones', 'Phones'), ('private_lessons', 'Private Lessons')], max_length=20)),
                ('image_url', models.URLField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Bitcoin.svg/1200px-Bitcoin.svg.png')),
                ('description', models.TextField()),
                ('owner_id', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketplace.item')),
                ('item_id', models.IntegerField(blank=True, default=None, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('model', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('year', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('processor', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('graphics_card', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Computers',
            },
            bases=('marketplace.item',),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketplace.item')),
                ('item_id', models.IntegerField(blank=True, default=None, null=True)),
                ('brand', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('model', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('year', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('operating_system', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('processor', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('camera_specifications', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('battery_capacity', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Phones',
            },
            bases=('marketplace.item',),
        ),
        migrations.CreateModel(
            name='PrivateLesson',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketplace.item')),
                ('item_id', models.IntegerField(blank=True, default=None, null=True)),
                ('tutor_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('lessons', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Private Lessons',
            },
            bases=('marketplace.item',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketplace.item')),
                ('type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('model', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('year', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('color', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('engine_displacement', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fuel_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('transmission_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('mileage', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            bases=('marketplace.item',),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.item')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
